### ISSUE TITLE
External issue tracking

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1156]
_This is a place to track issues we need to complete that are in other repositories. Feel free to add to it by editing the body._

- [x] central: [Exception thrown parsing JS exception](https://github.com/github/central/issues/293)
- [ ] desktop.github.com: [Redesign for Desktop TNG](https://github.com/github/desktop.github.com/issues/49)
- [x] desktop.github.com: [Autolink #issue references to their issue](https://github.com/github/desktop.github.com/issues/51)
- [x] [Open source checklist](https://github.com/github/open-source-releases/issues/25)
- [ ] [Scrub](https://github.com/desktop/desktop-secrets/issues/1)
- [x] guide for setting up Git on the command line (Windows-specific) - https://github.com/github/documentation/pull/876#issuecomment-294843465
