### ISSUE TITLE
Design Sync-up Agenda (April 11)

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#1164]
Hey everyone! I'm opening this issue to serve as an agenda for a weekly design sync-up that @niik and I've set up.

Please comment on this issue with any link to issues or comments if there's something you'd like for us to take a look at. We'll summarize and create tasks at the end of this issue.

[Link to opened issues that need design](https://github.com/desktop/desktop/issues?q=is%3Aopen+is%3Aissue+label%3Aneeds-design)

---

Here's a list of topics I would love to talk about (but we don't have to hit all of them):

- [x] [Publish Repository org dropdown polish](https://github.com/desktop/desktop/issues/1151)
- [x] Are the segmented controls too narrow?
- [x] Discard all changes feels weird as a context menu item on one item
- [x] [show progress on long-running background operations (push/pull/checkout) ](https://github.com/desktop/desktop/issues/953)
- [x] [Link focus styles and implementation](https://github.com/desktop/desktop/issues/1127)
- [x] [Expandable commit summary](https://github.com/desktop/desktop/pull/1080)
- [x] Welcome flow polish + illustrations
- [x] Window titlebar active/inactive state (out of focus)
- [x] Desktop landing page
- [ ] ["Open Conflict Resolution Tool" button](https://github.com/desktop/desktop/issues/71)
- [ ] [Set conflict resolution tool](https://github.com/desktop/desktop/issues/68)
