### ISSUE TITLE
Design Sync-up Agenda (April 18)

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1174]
Opening this up early so we can collect feedback on what the team wants us talk about. Bear in mind that this will be a slightly short cycle for us as I will be out Friday and Monday due to them being public holidays in Sweden.

#### Action items from [previous week](https://github.com/desktop/desktop/issues/1164)

- [x]  @niik will try to put all the shared styles between the textbox and the select compoment into a shared mixin
- [x] @donokuda is gonna take a stab at increasing height of tab bars
- [ ] @niik will write up issue(s) for discarding changes
- [x] @niik will write up an issue about showing progress in toolbar buttons
- [x]  @donokuda is gonna publish a branch with the focus ring polyfill and some styles that we can play around with.
- [ ] We'll ponder on a new approach for the expandable commit message and whoever gets inspiration first will make up a mock and present at a future weekly design meeting.
- [x] @donokuda will work on polishing the welcome flow as part of his general polish overhaul. @donokuda also has alot of other stuff on his plate so @niik might jump in if needed
- [x]  @donokuda Is gonna have a chat with James and get an update on how the work is progressing
- [x] @niik will open up a PR with blurred styles for the title bar to be discussed further
- [x] @donokuda is gonna talk with @joshaber about the desktop landing page

### Agenda

 - [x] @niik: Acknowledgements refinements
 - [ ] @donokuda: [Repo dropdown empty state](https://github.com/desktop/desktop/issues/871#issuecomment-293669639)
- [x] @donokuda: [App Icon](https://github.com/desktop/desktop/issues/1221)
- [x] @donokuda: [Welcome flow](https://github.com/github/creative/issues/1362)
- [x] @niik: Should we put some primer colors into some variables?

cc @desktop/core
