### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1368]
**May 16 @ 10am PST**

#### Launch
- [x] Land docs changes (@bwestover)
- [x] [Scrub](https://github.com/desktop/desktop-secrets/issues/1) (@joshaber)
- [x] Flip the open source switch (@joshaber)
- [x] Merge the [beta landing page PR](https://github.com/github/desktop.github.com/pull/53) (@donokuda)
- [x] Publish the [GitHub engineering blog post](https://github.com/github/githubengineering/pull/199) (@joshaber)
- [x] Publish the GitHub blog post (Marketing)

#### Post-Launch
- [x] Verify CI and badges work.
- [x] Disallow integrations on the org level.

**Comment by joshaber** [comment]
💥
