### ISSUE TITLE
Design Sync-up Agenda (June 7)

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1816]
This is a tentative agenda for the design sync-up between me and @donokuda, it's tentative because we won't be able to have our regularly scheduled fun-times on Tuesday as @donokuda is out taking some well-deserved time off. We'll try to make the sync-up happen on Wednesday instead but we might end up punting on it until next week.

Action items from the [last time we took notes](https://github.com/desktop/desktop/issues/1338)

- [x] @donokuda to follow up app icon with a couple more color variations (https://github.com/desktop/desktop/issues/1221)
- [x] @donokuda to check in with installation animation
- [x] @niik to continue work in the a11y branch
- [x] Someone to start design for showing long running commit processes
- [x] @donokuda to get the new Desktop site staged somewhere and tested out before we merge in.
- [x] @donokuda to also follow up with more content for the Desktop site
- [x] @donokuda or @niik to pull primer color variables into our stylesheets (#1713)
- [x] @niik to write up issue(s) for discarding changes
- [ ] @donokuda and @niik to ponder better ways to show an expandable commit message

New items to discuss

- [x] [Difficult to see the title bar on the window](https://github.com/desktop/desktop/issues/1717)
- [x] [Make staging line hunks more obvious](https://github.com/desktop/desktop/issues/1688)
- [x] [The default avatar should be local](https://github.com/desktop/desktop/issues/1621)
- [x] [Feature request - toggle full screen button](https://github.com/desktop/desktop/issues/1809)
- [x] [Scrolling diffs are cutoff after long commit message and description](https://github.com/desktop/desktop/issues/1742)
- [x] [Zoom And Enhance](https://github.com/desktop/desktop/issues/1720)
  - 29px list item heights doesn't scale well on 100% DPI
- [x] [Improve commit message writing experience](https://github.com/desktop/desktop/issues/1646)
- [x] [Ability to make the file list wider](https://github.com/desktop/desktop/issues/1588)
- [x] [Creating a branch is hidden in the File menu](https://github.com/desktop/desktop/issues/1575)
- [x] [Sign in screen tab index](https://github.com/desktop/desktop/pull/1513)
- [x] [Add link to copy SHA to clipboard](https://github.com/desktop/desktop/pull/1778)
- [ ] Make our blankslates a little friendlier <sup>[1]</sup>

----

<sup>[1]</sup> With regards to the "No file selected" and "No commit selected" blankslates ([via slack](https://github.slack.com/archives/D0M0SUNLV/p1496683627857715))
> While this message and image is technically accurate I wonder if we're focusing on the wrong thing
> As long as there are changes in the repository we ensure that you have a selection, right
> So what this means isn't as much that you haven't selected a file but rather that there aren't any changes at all
> So this messaging could be much more positive IMO
> Like "Nothing to commit :tada:" (but better)

**Comment by donokuda** [comment]
Notes taken from our sync today. @niik - feel free to add or edit in case I missed anything.

## Difficult to see the title bar on the window

Decided to not take action at this time but are open to any additional feedback.

*No action required*

## Make staging line hunks more obvious

After a bit of exploration, we're not confident that adding checkmarks solve the original discoverability problem of staging individual lines.

Regarding the checkmarks, we would like to see if more users are confused by the "selected/unselected" state before adding anymore elements to the UI.

*No action required for now*

## The default avatar should be local

We've fixed the issue of the avatar being local. We might explore a different default avatar but right now we're not considering it a high priority as it doesn't block anyone from using GitHub Desktop.

*No action required for now*

## Feature request - toggle full screen button

We'll take a cue from Chrome/YouTube and show a dialog explaining how to get out of fullscreen mode

## Scrolling diffs are cutoff after long commit message and description

For long commit summaries, we'll truncate at around 80 characters and move the remaining portion down to the description section.

We still want to rethink the expand/collapse commit messages interaction.

## Zoom and Enhance

Since this is a chromium bug only on Windows, we decided to not fix this for the time being since it might be fixed in a chromium update. If it becomes a continuing problem (and breaks our users workflows), then we'll revisit.

In the meantime, you can fix this by switching between the changes and history view.

*No action required*

## Improve commit message writing experience

Agree in general that we should allow vertical resizing of the commit form (as well as horizontal resizing of the sidebar.) The tiny font issue can be solved by zooming the app.

## Ability to make the file list wider

Also agree that we should allow a larger maximum width for the file list / sidebar. In the short term, let's allow the sidebar to be resized until there's no more space. We'll set a max width so that the branch and push/pull buttons aren't squished horizontally. In the long term, we can determine the max width dynamically based on how much space we need to fit information in the branch and push/pull button.

## Creating a branch is hidden in the file menu

In the case when someone is searching for a branch in the branch dropdown, we'll show text that says "You can create a new branch from the branch menu" with linking to the Create Branch dialog.

We're also considering the ability to create a new branch from the filter textbox by hitting <kbd>cmd/ctrl</kbd>+<kbd>Enter</kbd>

## Better compatibility with password managers

We'll rework the login screen so that the tab ordering is correct without having to explicitly setting the tab index.

## Add link to copy SHA to clipboard

Instead of having the SHA as a link, we'll allow users to select and copy the SHA. We'll also add a context menu to the commit list where you can select an action to copy the SHA to the clipboard as well as open the commit on GitHub.

We'll keep the "View on GitHub" link but replace the external link icon with the Octocat head icon.

## Make our blankslates a little friendlier

We'll discuss this at our next team summit.

**Comment by j-f1** [comment]
re: “Difficult to see the title bar on the window,” what about integrating the title bar and the toolbar on macOS. Mockups attached, although I haven’t moved the traffic lights down.
![dropdown closed](https://user-images.githubusercontent.com/25517624/26904563-7ee635d0-4bb0-11e7-8027-2e9a73c42c51.png)
![dropdown opened](https://user-images.githubusercontent.com/25517624/26904564-7efe0af2-4bb0-11e7-979d-16f67e781baf.png)

```css
#desktop-app-title-bar {
  display: none;
}
.toolbar {
  height: 37px;
}
.toolbar > :first-child button:first-child {
  padding-left: 75px;
}
.toolbar-button > button {
  padding: calc(var(--spacing) - 5px) var(--spacing);
}
```

**Comment by xt0rted** [comment]
> Instead of having the SHA as a link, we'll allow users to select and copy the SHA. ... We'll keep the "View on GitHub" link but replace the external link icon with the Octocat head icon.

That's how it currently works, but only with published commits since it's the link that's selectable.

Based on #1778, if both UI elements are going to stay, why remove the ability to click on the SHA to copy it? Making it only selectable just adds extra steps to what should be a simple action. I use this numerous times a day when I rebase and with how small the text is when running on 4k clicking is far easier than trying to select it and <kbd>Ctrl</kbd>+<kbd>C</kbd>.

If the reason to remove the click action is to avoid confusion, since it's styled like a link, could we just remove the link style but leave the action & tooltip?
