### ISSUE TITLE
[Tracking Issue] 1.1 Launch checklist - Pull Requests

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3129]
Target Date/Time: **Monday Feb 26 @ 1pm PST**

-- OPEN MILESTONE + POPULATE ISSUES --

- [x] **[HD]** Create help docs issue (@joshaber) - https://github.com/github/help-docs/issues/6086
- [x] **[BP]** Create blog post PR (@shiftkey) - https://github.com/github/blog-posts/pull/1260
- [x] **[GHD-MS]** Create marketing site issue (@joshaber) -  https://github.com/github/desktop.github.com/issues/80 
- [x] **[RT]** Create release tracker card (@nerdneha) - https://github.com/github/technology/projects/2

-- EXECUTION PHASE -- 

- [x] Notify help docs to start content strategy (@shiftkey)
- [x] Close all open issues in 1.1 milestone

-- FINALIZE THE RELEASE DATE --

- [x] Release to beta (`1.1.0-beta3`) (@nerdneha)
- [x] Flip feature flags and move to stable (@shiftkey)
- [x] **[QA]**  QA signoff (@tierninho)
- [x] **[HD]** Help docs are ready to be merged - [staging links](https://github.com/github/help-docs/pull/6773#issuecomment-365768676) (@megbird) - https://github.com/github/help-docs/issues/6086 
- [x] **[BP]** Create draft for blog post - https://github.com/blog/2508-github-desktop-1-1 (@shiftkey + marketing)
- [x] **[GHD-MS]**  Put marketing site changes on staging (@donokuda) -
https://pages.ghe.io/desktop/desktop.github.com/

-- IT'S GO TIME: LAUNCH THE THING --
- [x] Update the changelog for `1.1.0` (@iAmWillShepherd) (before 12:15pm PST)
- [x] Release to Prod as `1.1.0` (@nerdneha) (12:30pm PST)
- [x] **[HD]** Merge the help docs PR (@megbird) - https://github.com/github/help-docs/issues/6086 (12:35pm PST)
- [x]  **[GHD-MS]** Merge marketing site PR - https://github.com/github/desktop.github.com/pull/88 (@donokuda)  (12:55pm PST)
- [x]  **[BP]** Publish blog post - https://github.com/blog/2508-github-desktop-1-1 (@shiftkey) (1pm PST)
- [x] Release to Beta `1.1.1-beta1` (@shiftkey) (1:05pm PST)
- [x] Tweet about it (@stephbwills) - https://travis-ci.org/desktop/desktop/builds/346528204
- [x] monitor haystack closely for any new errors for the next hour (until 2pm PST) https://haystack.githubapp.com/desktop?q=version%3A1.1.0
- [x] **[RT]** Update the tracker card (@nerdneha) - https://github.com/github/technology/projects/2 (2pm PST)
- [x] celebrate 🎉 (2pm+ PST)

**Comment by joshaber** [comment]
That's cold stalebot. Real cold.

**Comment by shiftkey** [comment]
> Release to Beta (do we need to do this??) (1:05pm PST)

This is a minor thing to:

 - ensure the latest fixes are also on beta
 - ensure we've got the versions right so that beta remains ahead of stable

Given how beta is currently ahead of stable and has all of the `master` changes, this isn't something I consider to be on the critical path. I'd do it later today, once things have settled down.

**Comment by nerdneha** [comment]
@shiftkey awesome! just updated to have you as lead for this

**Comment by nerdneha** [comment]
closing because we did the thing! our blog post is here: https://blog.github.com/2018-02-26-github-desktop-1-1-is-now-available/
