### ISSUE TITLE
1.2 Launch Checklist - Relationship between branches lite

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3955]
Date: ~Mon Apr 23~ ~Mon Apr 30~ ~Mon May 7~ Mon May 21 (if we can QA in time)

### Major Features
* Compare Branches Feature Tracker https://github.com/desktop/desktop/issues/3956
* Multi-file select https://github.com/desktop/desktop/pull/4188

#### OPEN MILESTONE + POPULATE ISSUES ✅ 

- [x] **[HD]** Create help docs issue - https://github.com/github/help-docs/issues/7091
- [x] **[BP]** Create blog post PR - https://github.com/github/blog/pull/279
- [x] **[GHD-MS]** Create marketing site issue - https://github.com/github/desktop.github.com/issues/99
- [x] **[RT]** Create release tracker card (@nerdneha) - https://github.com/github/technology/projects/2#card-9456023

#### EXECUTION PHASE

- [x] Notify help docs to start content strategy (@iAmWillShepherd)
- [x] Close 1.1.x milestone - https://github.com/desktop/desktop/milestone/13
- [x] Close all open issues in 1.2 milestone - https://github.com/desktop/desktop/milestone/12
- [x] **[HD]** help docs PR is created - https://github.com/github/help-docs/pull/7263
- [x] **[GHD-MS]** marketing site PR is created - https://github.com/github/desktop.github.com/pull/101
- [x] **[V]** Create video issue - https://github.com/github/video/issues/466
- [x] **[V]** Notify video to start video-ing - 

#### FINALIZE THE RELEASE DATE

- [x] Release to beta (latest beta on 4/27 can be downloaded [here](https://s3.amazonaws.com/github-desktop/releases/1.1.2-beta7-9e856ecf/GitHubDesktop.zip))
- [x] Flip feature flags for production and move to stable - https://github.com/desktop/desktop/pull/4584
- [x] **[QA]**  QA signoff: https://github.com/desktop/desktop/issues/4734
- [x] **[HD]** Help docs are ready to be merged 
- [x] **[V]** Gifs are created and in the blog post
- [x] **[BP]** Create draft for blog post
- [x] ~**[GHD-MS]**  Put marketing site changes on staging~
- [x] Update the changelog for `1.1.2`

#### IT'S GO TIME: LAUNCH THE THING
- [x] Release to Prod as `1.2.0`
- [x] **[HD]** Merge the help docs PR @megbird (https://github.com/github/help-docs/pull/7259)
- [x]  **[GHD-MS]** Merge marketing site PR
- [x]  **[BP]** Publish blog post
- [x] Release to beta as `1.2.0-beta1`
- [x] Tweet about it (social-media team does this)
- [x] announce in slacks: desktop-releases, desktop, desktop-users-at-gh, client-apps (post twitter + blog links)
- [x] monitor haystack closely for any new errors for the next hour
- [x] **[RT]** Update the tracker card
- [x] celebrate 🎉

**Comment by meaghanlewis** [comment]
I tested this with Beta version `1.1.2-beta4` on both Mac and Windows and think that this feature is working great. ✨

**Comment by nerdneha** [comment]
Just commented to point out the changes in the description:
 - push launch date back
 - add checkboxes for video

**Comment by RodenLuo** [comment]
This might be naive. But I cannot find this feature after tracking all the way to this issue. Is it up in the newest release? On Windows 11, GitHub version 3.3.8 (x64).

Specifically, I'm looking for the gray and orange dotted line feature in the figure below mentioned in #3956. Thanks! 

![](https://user-images.githubusercontent.com/1174461/30396666-3ba54c86-987f-11e7-8f18-a7bb7ea5f1a1.png)
