### ISSUE TITLE
[Feature Tracker - UNTNG] Upgrade nudge from classic to Desktop Electron

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#4285]
### Release Date Target
**marketing page release** - on or before Wednesday Morning 8am PT ✅ 
**macOS release** - Wednesday Morning 5/2: 8am PT ✅ 
**blog release** - Wednesday Morning 5/2: 10am PT ✅ 
**Windows release** - Wednesday Afternoon 5/2: 4pm PT ✅  

### Purpose

Since officially launching Desktop Electron in September, we have slowly narrowed the gap between number of Desktop Classic and Desktop Electron users but, according to our analytics, a significant portion of our users are on Desktop Classic.

We are still seeing some percentage of performance issues, bugs, and corresponding support questions for Desktop Classic who are unaware that we are developing on Desktop Electron now. In fact, the Desktop Classic apps says they are "up to date" when they are on a product that is no longer maintained.

This feature provides users on Desktop Classic (both Windows and macOS) a "gentle nudge" to update their version and no longer claims that they are up-to-date. 
* continued from initial discussion here: #2146

### Dependencies:
- [x] macOS work - #4286; PR: https://github.com/github/Mac/pull/6991
- [x] Windows work - #4287; PR: https://github.com/github/Windows/pull/6008
- [x] marketing page update - https://github.com/github/desktop.github.com/pull/98
- [x] analytics - https://github.com/github/analytics/issues/463
- [x] blog post from analytics - https://github.com/github/blog/issues/241

### Design
These are available within issues also!

Upgrade nudge:
![upgrade dialog macos](https://user-images.githubusercontent.com/1834387/37618321-34eb9d26-2bb6-11e8-8561-5d5d260ccf72.png)
![upgrade nudge windows](https://user-images.githubusercontent.com/1834387/37618338-40dd9738-2bb6-11e8-81c3-66e192411441.png)

Updated About:
![about dialog macos](https://user-images.githubusercontent.com/1834387/37618351-4abd59fa-2bb6-11e8-9305-39cc724f733a.png)
![about dialog windows](https://user-images.githubusercontent.com/1834387/37618360-4ef38134-2bb6-11e8-9291-f27141bf4231.png)

**Comment by gingerbeardman** [comment]
You should mention that after upgrading users will have to migrate their configuration and repos manually.

**Comment by nerdneha** [comment]
@gingerbeardman we entirely agree. we're working on some copy to have that on our marketing page (which users are directed to) to give people a heads up and for a suggestion on how to resolve. thanks for the suggestion!

**Comment by nerdneha** [comment]
FYI the marketing site is live! https://desktop.github.com/upgrade/classic/
a reminder that this our plan to release tomorrow:
macOS release - Wednesday Morning 5/2: 8am PT (@joshaber)
Windows release - Wednesday Afternoon 5/2: 4pm PT (@shiftkey)

**Comment by shiftkey** [comment]
@j-f1 :thumbsup: I'll see if I can get that copy tweaked

**Comment by gingerbeardman** [comment]
Any chance the copy change directly above can be done ASAP?

**Comment by joshaber** [comment]
Yes, thanks for the bump @gingerbeardman! We might continue to iterate on the copy, but I went ahead and landed a clarification @shiftkey wrote.

**Comment by nerdneha** [comment]
@telliott27 wrong a blog post about the progress from Desktop Classic -> Electron that just posted! 
https://blog.github.com/2018-05-02-everyones-moving-to-github-desktop/

**Comment by shiftkey** [comment]
The Windows Classic update is live :boom: ✨

**Comment by agisilaos** [comment]
Quick thought: The marketing [site](desktop.github.com/upgrade/classic) for the transition from the old to the new desktop app is really well done and I can definitely see it as the main homepage for the product. Is it something that you consider doing?

It perfectly describes some of the features of the new Desktop app so why not? 🤔

**Comment by shiftkey** [comment]
@agisilaos can you add this to #4021? That seems like the best place to gather that after we close this out.

**Comment by nerdneha** [comment]
SUCCESS!!!!
Closing this issue 🎉

**Comment by mikeytag** [comment]
| a significant portion of our users are on Desktop Classic.

I'm waiting for something like this to make it's way into the Electron version. I settled into a great flow that centers around the visual reference of the tree and the ease of the "Update from" button.

![68747470733a2f2f676974687562656e67696e656572696e672e636f6d2f696d616765732f63726f73732d706c6174666f726d2d75692d696e2d6769746875622d6465736b746f702f636f6d70617269736f6e2d67726170682d6f732d782e706e67](https://user-images.githubusercontent.com/219403/40862372-2801d3b2-65a1-11e8-8c18-c07318c6f047.png)

**Comment by dmitriz** [comment]
@nerdneha 

This nudge is sadly harming users of old OSX for whom the Electron version is unavailable.
And replacing the old version that used to work perfectly fine by its update that refuses to install on the same OS is twice as sad.
