### ISSUE TITLE
[1.1.1 Release] Patch Release Tracker

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#4295]
Target Date+Time to Release `1.1.1` (patch): **Monday Mar 26 @ 10am PST**

### Pertinent Info
**Changelog:** https://github.com/desktop/desktop/blob/master/changelog.json#L7-#L32
**Major shipped features:** none
**Status**: Shipped! All future patches will be queued for `1.1.2+

### Major design facing changes (might affect screenshots)
* Toolbar contrast - https://github.com/desktop/desktop/pull/4227
* Sign in prompt has the password link moved - https://github.com/desktop/desktop/pull/4283
* Placeholder image changed when no pull requests found - https://github.com/desktop/desktop/pull/3973
* Alert icon for missing repositories in the repo list - https://github.com/desktop/desktop/pull/4258#issuecomment-373731314
* Scalable "diff too large" image and showing a diff after identified as too large to show through a button - https://github.com/desktop/desktop/pull/4050
* "No Repositories" text on dropdown if there are no repositories - https://github.com/desktop/desktop/pull/4268
* Updated gitignore dialog message when not on default branch - https://github.com/desktop/desktop/pull/4153#issuecomment-370488495
* Context menu when right-clicking on description - https://github.com/desktop/desktop/pull/3886
* Context menu when right-clicking on changed file list - https://github.com/desktop/desktop/pull/4230

#### Week Before (Mon Mar 19)
- [x] Release to beta (`1.1.1-beta3`) (@shiftkey)
- [x] QA signoff (@tierninho)
- [x] Create help docs issue to assess need for help-docs updates (@nerdneha) - https://github.com/github/help-docs/issues/7032

#### Thursday Before (Thurs Mar 21)
- [x] Open PR for Changelog for prod (`1.1.1`) - https://github.com/desktop/desktop/pull/4310

#### Day Of (Mon Mar 26)
- [x] Merge PR for Changelog for prod (`1.1.1`) (10am PST) - https://github.com/desktop/desktop/pull/4310
- [x] Release to Prod as `1.1.1` (@nerdneha) (10:05am PST)
- [x] Confirm successful `production` release via desktop application (10:30am PST)
- [x] Release to Beta to ensure they're on the latest code `1.1.2-beta1` (@nerdneha) (10:35am PST)
- [x] Confirm successful `beta` release via desktop application (11am PST)
- [x] monitor haystack closely for any new errors for the next hour (until 12pm PST) https://haystack.githubapp.com/desktop?q=version%3A1.1.1
- [x] celebrate...ish 🎉 (12pm+ PST)

#### After (week of Mar 26)
- [x] Finish content strategy plan for help-docs - https://github.com/github/help-docs/issues/7032
- [x] Release updated help-docs - https://github.com/github/help-docs/issues/7032

**Comment by shiftkey** [comment]
@nerdneha is this good to close out?

**Comment by nerdneha** [comment]
@shiftkey not until we get the help-docs rolled out, those are the open checkboxes

**Comment by shiftkey** [comment]
@nerdneha I think the Help docs updates were deployed a few hours ago, feel free to confirm and close this out :tada:

**Comment by shiftkey** [comment]
This has been wrapped up!
