### ISSUE TITLE
Detect Merge Conflicts

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4588]
**Goal**: As a user and consumer, when I am considering merging another branch into my own and _before merging_, I want to:
 * know whether I'll get into a conflict
 * be warned on how bad the conflict will be 
so that I can choose the best time to merge and be mentally prepared for it.

### Background
Built upon the [Compare Branch feature](https://github.com/desktop/desktop/issues/3956) that's about to land in 1.2. This is demonstrated in the initial mockups as a message below the merge button, like this:

<img width="236" alt="conflict-mockup" src="https://user-images.githubusercontent.com/359239/39558810-1b09433a-4ed5-11e8-87ba-19d7c57d90e0.png">

Implementation-wise, this is how we will accomplish the goal:
 - **know whether I'll get into a conflict** = test merging another branch without actually performing the merge 
 - **be warned on how bad the conflict will be** = display a number of files that will be conflicted if the user decides to proceed

### Interactive Example

I'm going to use https://github.com/desktop/desktop/pull/3675 as an example here, because this currently has a merge conflict.

#### Web Editor Flow

Here's what you see when you view the pull request:

<img width="726" src="https://user-images.githubusercontent.com/359239/39559043-a60edf5c-4ed6-11e8-8dad-93412db9caf3.png">

If we try and resolve this conflict in the editor, we see that it's just one file and one conflicted change:

<img width="1200" src="https://user-images.githubusercontent.com/359239/39559094-0ee2ca3e-4ed7-11e8-8c94-d25521080ab2.png">

#### Current Compare Branch Flow

There's no indicator when you compare to `master` that you're gonna have a bad time:

<img width="409" src="https://user-images.githubusercontent.com/359239/39559263-2fa7be2c-4ed8-11e8-811e-230defa9d45f.png">

When you merge `master` into the PR branch, you'll see this error:

<img width="693" src="https://user-images.githubusercontent.com/359239/39559268-3f344996-4ed8-11e8-82ac-052f7314be2a.png">

And when you switch to the Commit tab you'll see there's our conflicted file to resolve:

<img width="1211" src="https://user-images.githubusercontent.com/359239/39559279-506d1404-4ed8-11e8-9132-6cd4edaa3c46.png">

### Command Line Example

If you use `git merge --no-commit [other-branch]` to test this, it will still apply the result to the index - requiring a `git merge --abort` to undo the test merge. So how can we do this in Git _without_ actually performing the merge?

The classic Windows version of Desktop used [libgit2sharp](https://github.com/libgit2/libgit2sharp/) to  detect any merge conflicts, and as we're not interested in adding additional dependencies we need to figure out how to do this using `git.git`. Thankfully we have `git merge-tree`.

[`git merge-tree`](https://git-scm.com/docs/git-merge-tree) takes three arguments. In order:

 - `<base-tree>` - this is a common ancestor to both branches
 - `<branch1>` - this is the target branch for the merge ("ours" in Git terminology)
 - `<branch2>` - this is the source branch for the merge ("theirs" in Git terminology)

For the example in #3675, we can work out the `base-tree` SHA like this:

```
$ git merge-base pr/3675 master
c46391569aa99773c99bf8028753ba225df0678d
```
 
Then we can execute `git merge-tree`:

```
$ git merge-tree c46391569aa99773c99bf8028753ba225df0678d pr/3675 master
merged
  result 100644 41d8e9e745215d5ba5f382f949f6f4167ace4754 .github/ISSUE_TEMPLATE.md
  our    100644 65c8c0a5f5c37299d369ce4811128ae829368d2d .github/ISSUE_TEMPLATE.md
@@ -2,7 +2,7 @@
 First and foremost, we’d like to thank you for taking the time to contribute to our project. Before submitting your issue, please follow these steps:
 
 1. Familiarize yourself with our contributing guide:
-	* https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md#contributing-to-github-desktop
+	* https://github.com/desktop/desktop/blob/master/.github/CONTRIBUTING.md#contributing-to-github-desktop
 2. Check if your issue (and sometimes workaround) is in the known-issues doc:
 	* https://github.com/desktop/desktop/blob/master/docs/known-issues.md
 3. Make sure your issue isn’t a duplicate of another issue
merged
  result 100644 16f2723406e57be8ea6ac3501f148e5c89b6442f app/package.json
  our    100644 d7ae9a501991fb77213d5228ec2232d8882e8457 app/package.json
@@ -3,7 +3,7 @@
...
```

Git emits the merge result to `stdout`, and it's a format that seems pretty easy to parse:

 - the first line is the a keyword representing the result - `merged`, `added in remote`, `removed in remote`, `changed in both` seem to be the potential values (there might be others)
 - then one or more lines, indented by two spaces, containing the file mode, blob and paths to the contents representing the merge result 

```
  base   100644 3f546193411ef428c7563a87efa8645326e8ee37 yarn.lock
  our    100644 a77184dc2241173e769e2be6feccb7248aec4fb2 yarn.lock
  their  100644 fd340f7005ceda34a5d8c6dc7dce20bf35b0253a yarn.lock
```

 -  Lastly, the unified diff of the merge result

Our conflicted file looks like this in the output from `git merge-tree`:

```
changed in both
  base   100644 78eb74f896151b4acefbb48dfbb920cd79aefc6e package.json
  our    100644 e821187bff2cd846836ef3f8fdffe86703f92251 package.json
  their  100644 643893279bcbef680b0cb3e1f3835702f4fe05bf package.json
@@ -13,6 +13,7 @@
     "test:setup": "ts-node -P script/tsconfig.json script/test-setup.ts",
     "test:review": "ts-node -P script/tsconfig.json script/test-review.ts",
     "postinstall": "cd app && yarn install --force && cd .. && git submodule update --recursive --init && yarn compile:tslint",
+<<<<<<< .our
     "start": "cross-env NODE_ENV=development ts-node -P script/tsconfig.json script/start.ts",
     "start:prod": "cross-env NODE_ENV=production ts-node -P script/tsconfig.json script/start.ts",
     "debug": "cross-env NODE_ENV=development ts-node -P script/tsconfig.json script/debug.ts",
@@ -20,6 +21,14 @@
     "compile:prod": "cross-env NODE_ENV=production parallel-webpack --config app/webpack.production.ts",
     "build:dev": "yarn compile:dev && cross-env NODE_ENV=development ts-node -P script/tsconfig.json script/build.ts",
     "build:prod": "yarn compile:prod && cross-env NODE_ENV=production ts-node -P script/tsconfig.json script/build.ts",
+=======
+    "start": "cross-env NODE_ENV=development node script/start",
+    "start:prod": "cross-env NODE_ENV=production node script/start",
+    "compile:dev": "cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js",
+    "compile:prod": "cross-env NODE_ENV=production parallel-webpack --config app/webpack.production.js",
+    "build:dev": "yarn compile:dev && cross-env NODE_ENV=development ts-node script/build.ts",
+    "build:prod": "yarn compile:prod && cross-env NODE_ENV=production ts-node script/build.ts",
+>>>>>>> .their
     "package": "ts-node -P script/tsconfig.json script/package.ts",
     "generate-octicons": "ts-node -P script/tsconfig.json script/generate-octicons.ts",
     "clean:tslint": "rimraf tslint-rules/*.js",
@@ -99,7 +108,7 @@
     "tslint-microsoft-contrib": "^5.0.3",
     "tslint-react": "^3.5.1",
     "typescript": "^2.8.1",
-    "typescript-eslint-parser": "^14.0.0",
+    "typescript-eslint-parser": "^15.0.0",
     "webpack": "^3.10.0",
     "webpack-bundle-analyzer": "^2.11.1",
     "webpack-dev-middleware": "^2.0.3",
```

What's useful here is that we can see the merge conflict markers inline, which is the same output as you get when you do a `git merge master` into `pr/3675`.

For reference, a different `changed in both` entry which was auto-merged looks like this:

```
changed in both
  base   100644 3f546193411ef428c7563a87efa8645326e8ee37 yarn.lock
  our    100644 a77184dc2241173e769e2be6feccb7248aec4fb2 yarn.lock
  their  100644 fd340f7005ceda34a5d8c6dc7dce20bf35b0253a yarn.lock
@@ -7267,9 +7267,9 @@
   version "0.0.6"
   resolved "https://registry.yarnpkg.com/typedarray/-/typedarray-0.0.6.tgz#867ac74e3864187b1d3d47d996a78ec5c8830777"
 
-typescript-eslint-parser@^14.0.0:
-  version "14.0.0"
-  resolved "https://registry.yarnpkg.com/typescript-eslint-parser/-/typescript-eslint-parser-14.0.0.tgz#c90a8f541c1d96e5c55e2807c61d154e788520f9"
+typescript-eslint-parser@^15.0.0:
+  version "15.0.0"
+  resolved "https://registry.yarnpkg.com/typescript-eslint-parser/-/typescript-eslint-parser-15.0.0.tgz#882fd3d7aabffbab0a7f98d2a59fb9a989c2b37f"
   dependencies:
     lodash.unescape "4.0.1"
     semver "5.5.0"
```

By streaming the output from Git into a parser, I think we can cheaply aggregate the number of files that have changed, as well as _which_ files are conflicted, without having to actually perform the merge and update the index.

## Task List (TBC)

 - [x] build a merge result parser that can read the results from `git merge-tree` and generate a summary to emulate merging
 - [x] build the Git infrastructure to generate the merge result between two branches
 - [x] execute merge test in `AppStore` when branch selected and has `ahead` commits to merge
 - [x] add UI to Compare tab for displaying the merge conflict result (if found)
 - [x] incorporate analytics - #5550

#### Related
- [ ] inform help-docs on user-facing updates
- [ ] update marketing page screenshots and add feature page
- [ ] update blog post for GitHub blog

**Comment by shiftkey** [comment]
@billygriffin I've switched this label to `user-research` based on our discussion today

**Comment by shiftkey** [comment]
I've pushed up a branch https://github.com/desktop/desktop/compare/parsing-merge-tree-result?expand=1 that shows what the heavy lifting of merge conflict detection might look like. Testing it on a Windows 7 VM, these are the timings for one of the chronic cases from VSCode

<img width="514" src="https://user-images.githubusercontent.com/359239/42654566-66f1da4a-85ef-11e8-86fa-2290fae8e592.png">

The timings on this are pretty interesting:

<img width="380" src="https://user-images.githubusercontent.com/359239/42654582-7b441cec-85ef-11e8-9289-7e5426087a0e.png">

 - `getMergeBase` needs to be done to figure out the common ancestor between the two refs, but if this method returns one of the known refs it means this branch is only behind, or only ahead, so it can probably be done as a fast-forward merge (but we don't do that currently)

 - `mergeTree` what we have when a ref is both ahead and behind the other ref, and is the work required by Git to identify whether there are any merge conflicts that the user needs to do

 - `parseMergeResult` is the new code to parse the output from Git and identify whether there are any conflicts that the user will have to work with

If we continue down this path, the UX should definitely support being executed and updated asynchronously.

**Comment by shiftkey** [comment]
Going to rework the prototype before opening a PR, but wanted to add a note here about the UX.

This is how it currently looks when we combine the merge commit hint with the message about what this merge will do to the repository:

<img width="282" src="https://user-images.githubusercontent.com/359239/44111509-09938a70-9fd9-11e8-9873-6f20bd440692.png">

This is making the area rather busy, and I have a suggestion to combine these two messages to keep things simple:

The "clean merge" message essentially becomes ` ✅This will merge XY commits from [branch] into [branch]`, and the "conflicts detected" becomes `⚠️ There will be X conflicts after merging [branch] into [branch]`, with a loading spinner in between.

This helps keep the context focus on what the next action will be, but I'm open to other ideas around how we're using this area to communicate information.

**Comment by billygriffin** [comment]
Does this account for when a user tries to merge via the notification for diverging from master and/or merging from the file menu in `Branch > Merge into current branch` and `Branch > Update from default branch`?

**Comment by shiftkey** [comment]
@billygriffin not currently - my initial work was focused on the compare tab because that's what we had the mocks for

**Comment by ampinsk** [comment]
> The "clean merge" message essentially becomes ✅This will merge XY commits from [branch] into [branch], and the "conflicts detected" becomes ⚠️ There will be X conflicted files when merging [branch] into [branch], with a loading spinner in between.

+1 on the above wording (I edited to incorporate @billygriffin's edits). @shiftkey I might be missing some context but why would there be a loading spinner in between?

> Does this account for when a user tries to merge via the notification for diverging from master and/or merging from the file menu in Branch > Merge into current branch and Branch > Update from default branch?

I'm going to chat with @donokuda about the intended experience for these workflows and update back here 👍

**Comment by billygriffin** [comment]
@shiftkey Thanks! Do you anticipate the conflicts check hindering performance in the way that the background work for repo indicators did or in any other ways we may not have thought about yet?

**Comment by shiftkey** [comment]
@billygriffin no, this should only fire when the user is interacting with the compare tab to change branches (or whatever flows we decide to settle on for this) so it should be constrained to that action.

**Comment by nerdneha** [comment]
Are there any thoughts on adjusting the `Merge` button color based on ✅ or ⚠️? (ex: a pretty green vs. a pretty red/maroon)

I feel like there might have been some discussion so apologies if I missed it!
(cc @desktop/design, @billygriffin and @shiftkey)

**Comment by billygriffin** [comment]
Here's the web UI for that case @nerdneha @desktop/design. 

<img width="697" alt="screen shot 2018-08-28 at 8 42 33 am" src="https://user-images.githubusercontent.com/5091167/44730530-68868080-aa9e-11e8-9c63-1aa8b7c335c6.png">

**Comment by billygriffin** [comment]
@donokuda I'm wondering if they actually get anything out of clicking that button though if there will be conflicts? Does it add any value at all, or does it just put them into a more confusing state? If it's the latter, consistency with dotcom feels appropriate to me (having the button not clickable), but if there is some value I'm not grasping, then it seems totally reasonable to continue to allow the click.

**Comment by donokuda** [comment]
> @donokuda I'm wondering if they actually get anything out of clicking that button though if there will be conflicts? Does it add any value at all, or does it just put them into a more confusing state? If it's the latter, consistency with dotcom feels appropriate to me (having the button not clickable), but if there is some value I'm not grasping, then it seems totally reasonable to continue to allow the click.

I think the "Resolve Conflicts" button in your screenshot is closer to the flow I was thinking of when someone clicks the "Merge X into Y" button in Desktop. Since we're giving them a heads up about the merge conflicts ahead of time, my assumption is that they won't be caught off-guard and (hopefully) know the next steps in resolving the conflict.

Your comment did raise a couple of thoughts that we might want to consider (though I would consider it out of scope):

1. The ability to back out of the merge if users want to NOPE out of the merge attempt (like `git merge --abort`)
2. Prevent the ability to accidentally commit conflicts by disabling the commit button until all conflicts are resolved (or introduce some sort of "I know what I'm doing" safeguard.)

Let me know if that helped and I'll to do my best to clarify! 😄

**Comment by donokuda** [comment]
Also wanted to capture some stuff @ampinsk and I chatted about yesterday regarding: 

> Does this account for when a user tries to merge via the notification for diverging from master and/or merging from the file menu in Branch > Merge into current branch and Branch > Update from default branch?

I think it would be ideal if we are able to show the merge-ability status in the `Branch > Merge into current branch` menu option. I was thinking since the layout of the button and status are similar, we could use the same treatment in both places.

![image](https://user-images.githubusercontent.com/1174461/44737076-d5514900-aaa5-11e8-867c-b49e863c65e7.png)

(I noticed that there are a few inconsistencies with the UI under the merge button, but we can clean that up in a separate PR)

With regards to the `Branch > Update from default branch`, I don't think flow is fully thought through and we might want to address this outside of 1.4. For example, it will attempt to merge the default branch into the working branch but doesn't give any success feedback.

> On slower machines we shouldn't assume this check will finish immediately, so I was thinking about how to show "we're checking things". I'm sure there's other chronic bottlenecks like "omg there's conflicts in every file" to consider as part of this flow.

I accidentally found myself in a design rabbit hole when I went to make examples of each potential state while incorporating the new text, but here's how I was thinking we could show the loading / merge-ability states:

<img width="891" alt="loading states" src="https://user-images.githubusercontent.com/1174461/44736844-2ad92600-aaa5-11e8-929b-fd74a3d7512c.png">

These could probably still be iterated on, so I'd love @ampinsk and y'alls takes on it 😄 We could also try what @nerdneha suggested with a different button treatment for when merge conflicts will occur.

**Comment by billygriffin** [comment]
@donokuda Agreed about reusing the styles for the three "normal" cases (and excluding "Update from default branch"):

1. Regular merging via compare branch flow
2. `Branch > Merge into current branch`
3. Merging via NDDB

> I accidentally found myself in a design rabbit hole when I went to make examples of each potential state while incorporating the new text, but here's how I was thinking we could show the loading / merge-ability states:

I love these, they're really good. Only minor nit would be to downcase "check" in "Pending Check."

Re: the clickability of the merge button in your previous comment, it sounds like there is actually utility in being able to click "Merge" anyway. That the clicking the button triggers the conflict, which introduces the ways to resolve those conflicts in your chosen way (for example, by hopping over to Atom and using the conflict resolution tool there).

**Comment by shiftkey** [comment]
Bumping this to call out a scenario I encountered today.

Some repositories have a `gh-pages` branch that's used by a repository to publish to GitHub Pages. This is a separate Git history, so the current steps to find for a common ancestor commit and test merging doesn't work here. This is also a workflow that most users would typically want to do ever (merging your website into the code?!!?!?), so it's not really something I want to focus too much on.

This is what I've been noodling on to display to the user in this case (don't worry about the font selection, this is me just running some atypical settings on Windows):

<img width="279" src="https://user-images.githubusercontent.com/359239/44865239-2d2fb180-ac58-11e8-915d-78c14a1bfacd.png">

I settled on the alert indicator because it's merging two separate histories, but I'm open to better wording here.

You can't actually merge these two histories together, because you need to pass `--allow-unrelated` when you call `git merge`, and you currently hit this error:

<img width="428" src="https://user-images.githubusercontent.com/359239/44865351-7b44b500-ac58-11e8-9eb1-f2a207aec971.png">

I stumbled upon this ages ago in https://github.com/desktop/desktop/issues/1484 with different steps to trip it.

We could also make this a non-issue by ensuring the **Compare To Branch list is only populated with branches that are reachable from your current branch**. I'm not sure what's involved here to compute that list, and a quick glance at `git branch` didn't show a simple flag to use.

**Comment by j-f1** [comment]
How about disabling switching out the entire merge/merge result card for an info message when histories are separate?

**Comment by billygriffin** [comment]
I would be onboard with that. It seems like an edge case that would be nicely solved by @j-f1 / @donokuda's suggestion. The X and disabled button is nice and aligns with the current paradigm.

**Comment by shiftkey** [comment]
This has been resolved in #5495 and will be published with 1.4.0

**Comment by hamzaneffati** [comment]
dfghdf
