### ISSUE TITLE
Move unpublished commits to new branch

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#4647]
## Goal
As a user, before I accidentally made a bunch of commits on the wrong branch (ex: protected or master), I want the app to warn me and guide my commits to a new branch so that I don't have to use command line magic to get them to a new branch or reset my work and risk losing everything.

#### Background
Inspired by previous issue [Move unpublished commits on master to new branch](https://github.com/desktop/desktop/issues/1021) that's about to land in 1.2. 

Colloquially known as **New Branch, Maybe?**

## Solution
[to be filled out by @niik]

#### Alternatives Considered
[to be filled out by @niik]

#### Task List
- [ ] a
- [ ] b
- [ ] c
- [ ] incorporate analytics

#### Mockups
[@niik put mockups here]

#### User Testing Strategy
[@niik/@nerdneha describe when/what/how for user testing]

#### Related
- [ ] inform help-docs on user-facing updates
- [ ] update marketing page screenshots and add feature page
- [ ] update blog post for GitHub blog

**Comment by billygriffin** [comment]
I'm going to close this since we have this work captured in https://github.com/desktop/desktop/issues/1021.
