### ISSUE TITLE
Testing notes for 1.2.0 release

### ISSUE THREAD

**Issue by meaghanlewis** [desktop/desktop#4734]
#Checklist of testing scenarios and notes of anything interesting found during testing.

Testing using: 1.1.2-beta7
Test on: Mac and Windows

## Manifest scenarios
<details>
<summary>Welcome Flow</summary>

  - [x] `Sign in to Github.com` link
    - [x] `Sign in` successful if valid username/email and password
      - [x] If 2FA activated, user sent auth code to enter (test SMS and authenticator app)
        - [x] User can reissue auth code with `Resend SMS` link
	- [x] Sign in successful with active 2FA code, user goes to Configure Git
	  - [x] User sees Repository landing page if sign in successful
	  - [x] Error message if code is wrong or inactive 
      - [x] Error message if incorrect username/email or password
    - [x] `Cancel` returns to initial Welcome Flow
    - [x] `Sign in using your browser` opens default browser
      - [x] Browser login, "authorize" GitHub Desktop, “accept” link
        - [x] If successful, Desktop shown in `/settings/applications` in user profile
  - [x] `Sign in to Enterprise` link (works with v2.8 and up)
    - [x] `Continue` successful if server address is valid, else error message
      - [x] `Sign in using your browser` opens default browser
        - [x] Browser login, [insert custom security measure], Authorize GitHub Desktop, “accept” link
    - [x] User goes to Configure Git if successful
    - [x] `Cancel` returns to initial Welcome Flow
    - [x] User served generic message if not authorized to access Enterprise server
  - [x] Skip "username+password" step
    - [x] Configure Git
      - [x] Name and email pulled from global `.gitconfig` file, if configured
  	- [x] If recognized, your avatar is present in example commit; gravatars not recognized
      - [x] `Continue` okay if fields populated or blank
  	- [x] Valid login credentials from github.com or Enterprise carried through
	  - [x] User sees Repository landing page if sign in successful
  - [x] Usage Data
    - [x] Checked by default; user can uncheck. (Should not be checked if user on free plan only.)
      - [x] Clicking `Finish`, and user is signed in successfully to Desktop
    - [x] `Cancel` returns to initial Configure Git page
</details>

<details>
<summary>Repositories landing page</summary>

  - [x] Create New Repository (Mac: `⌘N`; Windows: `Ctrl+N`)
    - [x] Modal opens with name, path (choose option), readme (unchecked), git ignore, license. Name and path mandatory.
      - [x] If repository name is over 100 characters, warning message is surfaced in modal
      - [x] If repository contains URL-hostile characters, show error message
    - [x] `Create Repository` button adds new repo, which is added to Repo list
    - [x] `Cancel` button does not save any changes made; modal closed
  - [x] Clone a Repository (Mac: `⇧⌘O`; Windows: `Ctrl+Shift+O`)
    - [x] Enter valid URL or `username/repo/gist`, else error message
      - [x] If authentication error for Github.com, modal with username/password surfaced; `Cancel` or `Save and Retry` buttons
        - [x] If successful, repo is cloned
	- [x] Modal surfaces again if unsuccessful
      - [x] If authentication error for Enterprise, user redirected to Preferences
    - [x] Valid path can be entered or selected
      - [x] Local path is prepopulated; if not unique then error surfaced
    - [x] All repos from both GitHub.com and Enterprise are populated -- your repos are listed first, followed by org(s)
      - [x] User must be logged in to view list; else `Sign In` button present
      - [x] Results are filterable, and can be selected for cloning
    - [x] `Clone` creates repo at selected path
      - [x] Repo added to Repo list
    - [x] `Cancel` closes modal, no repo cloned
  - [x] Add a Local Repository (Mac: `⌘O`; Windows: `Ctrl+O`)
    - [x] Valid path can be entered or selected
    - [x] `Add repository` activated if repo path exists
      - [x] Repo added to Repo list
      - [x] If directory path not valid, 'Create a new repo' error message is present
    - [x] `Cancel` closes modal, no repo added
    - [x] Large repos (> 100MB) trigger Initialize Git LFS modal
      - [x] Link takes user to (`https://git-lfs.github.com/`)
      - [x] Local path to repo is displayed
      - [x] User can click `Cancel` or `Initialize Git LFS`
  - [x] Drag and drop repository
    - [x] User can drag existing local repository into Desktop
      - [x] Successful attempt adds repo to Repo list; else error message
</details>

<details>
<summary>Publishing a repository</summary>

  - [x] Publish Repository modal present if repo is unpublished and user clicks `Publish repository` button
    - [x] GitHub tab is default; Enterprise tab is also present
      - [x] User must be signed in to publish, else `Sign In` button present on tab
    - [x] Modal fields are Name, Description (optional), `Keep this code private` checkbox, Organization list (alpha order, tab-specific, if orgs exist), `Cancel` button, `Publish Repository` button
      - [x] Clicking `Publish Repository` button pushes repo to GitHub.com or Enterprise; `Cancel` button closes modal
        - [x] Repository is present on GitHub.com or Enterprise if published 
	- [x] 'Visibility can't be private error' shown, if user's plan is not sufficient
	- [x] A `.gitattributes` file is added to the repository as part of the initial commit
	- [x] If repo is forked and upstream remote does not match, then modal is surfaced with Ignore/Update button 
</details>

<details>
<summary>Application</summary>

  - [x] Minimize, Maximize, Close buttons work in top nav
      - [x] If user zooms in and quits app, settings should be retained when reopened
  - [x] Double-clicking local desktop icon opens the application (Mac only)
  - [x] Double clicking top nav bar toggles full-screen / last used screen-size (Mac only); Exit by (Mac: `^⌘f11`; Windows: `Alt`)
  - [x] Clicking Desktop icon in dock/taskbar opens the application
  - [x] Changing desktop icon name while app is open results in package error; closed app name change is successful
</details>

<details>
<summary>GitHub Desktop menu top-level</summary>

  - [x] About GitHub Desktop
    - [x] Current version shown
    - [x] Links to release notes (github.com), terms (modal), licenses (modal)
    - [x] Update banner shows `whats new` link and `retart now` link
    - [x] Update modal shows enhancements / bug fixes in latest build with `Install button`; user can X the banner
    - [x] Clicking the version number copies to clipboard
      - [x] Clicking `Check for updates` button produces "read-only volume" error message, with link for help
    - [x] Clicking `Check for updates` button timestamps last attempt
      - [x] If checking for update or download latest update, the `Check for updates` button is disabled
      - [x] Restarting the app automatically checks for updates
    - [x] `Close` button closes modal 
  - [x] Preferences/Options (Mac: `⌘,` Windows: `Ctrl+,`)
    - [x] Accounts
      - [x] GitHub.com name, handle, avatar, `sign out` button, if user signed in
      - [x] Enterprise handle, avatar, `sign out` button, if user signed in
      - [x] User can sign out of either account
      - [x] User can sign-in to both Enterprise and GitHub.com at same time  
    - [x] Git
      - [x] Username and email are displayed if `.gitconfig` configured for Welcome flow
      - [x] `Save` button saves any changes made
      - [x] `Cancel` button does not save any changes made; modal closed
    - [x] Advanced
      - [x] External Editor options shown in dropdown; else show "Install Atom?" link
      - [x] Shell options shown in dropdown
      - [x] Shared usage data option; selection carried through from Welcome flow
        - [x] `anonymous usage data` link opens https://desktop.github.com/usage-data/
        - [x] Check `stats-opt-out` value in Dev Tools > Application > Local storage > file://
      - [x] Confirmation dialogue for removing repositories is checked by default; user can toggle
          - [x] Check `ConfirmDiscardChanges` value in Dev Tools > Application > Local storage > file://
      - [x] Confirmation dialogue for discarding files is checked by default; user can toggle
          - [x] Check `ConfirmRepoRemoval` value in Dev Tools > Application > Local storage > file://
      - [x] `Save` button saves any changes made
      - [x] `Cancel` button does not save any changes made; modal closed
    - [x] Clicking `OK` closes modal
  - [x] Quit/Exit Desktop (Mac: `⌘Q`)
    - [x] Quitting/Exiting and reopening Desktop returns you to last visited repo
  - [x] Menu items are disabled any modal is present; MacOS-default menu items not applicable
</details>   

<details>
<summary>File top-level menu</summary>

  - [x] Create New Repository (Mac: `⌘N`; Windows: `Ctrl+N`)
  - [x] Clone a Repository (Mac: `⇧⌘O`; Windows: `Ctrl+Shift+O`)
  - [x] Add a Local Repository (Mac: `⌘O`; Windows: `Ctrl+O`)
  - [x] Options... (Windows only: `Ctrl+,`)
  - [x] Exit (Windows only; quits the app)
</details>

<details>
<summary>Edit top-level menu</summary>

  - [x] Undo (Mac: `⌘Z`; Windows: `Ctrl+Z`)
  - [x] Redo (Mac: `⇧⌘Z`; Windows: `Ctrl+Y`)
  - [x] Cut (Mac: `⌘X`; Windows: `Ctrl+X`)
  - [x] Copy (Mac: `⌘C`; Windows: `Ctrl+C`)
  - [x] Paste (Mac: `⌘V`; Windows: `Ctrl+V`)
  - [x] Select all (Mac: `⌘A`; Windows: `Ctrl+A`)
</details>

<details>
<summary>View top-level menu</summary>

  - [x] Show History (Mac: `⌘1`; Windows: `Ctrl+1`)
  - [x] Show Compare (Mac: `⌘2`; Windows: `Ctrl+2`)
  - [x] Show Repositories List (Mac: `⌘T`; Windows: `Ctrl+T`)
  - [x] Show Branches List (Mac: `⌘B`; Windows: `Ctrl+B`)
  - [x] Enter Full Zoom (Mac: `^⌘F`; Windows: `F11`)
  - [x] Reset Zoom (Mac: `⌘0`; Windows: `Ctrl+0`)
  - [x] Zoom In (Mac: `⌘=`; Windows: `Ctrl+=`)
  - [x] Zoom Out (Mac: `⌘-`; Windows: `Ctrl+-`)
  - [x] Toggle Developer Tools (Mac: `⌥⌘I`; Windows: `Ctrl+Shift+I`)
</details>

<details>
<summary>Repository top-level menu. (Only enabled if one repo present)</summary>

  - [x] Push (Mac: `⌘P`; Windows: `Ctrl+P`)
    - [x] Commits from repo pushed to .com; error message shown if conflicts
  - [x] Pull (Mac: `⇧⌘P`; Windows: `Ctrl+Shirt+P`)
    - [x] Commits from repo pulled from .com; error message shown if conflicts
  - [x] Remove
    - [x] Repo is removed from Repo List; confirmation dialogue shown if Preferences option enabled
  - [x] View on GitHub (Mac: `⌥⌘G`; Windows: `Ctrl+Alt+G`)
    - [x] Repo on .com is opened; must be logged in if private repo or Enterprise
  - [x] Open in Terminal/Command prompt (Mac: `^[tilde-sign]`; Windows: )
    - [x] Local repo is opened
    - [x] If git not installed, modal asks to Open with Git or Install Git
  - [x] Show in Finder/Explorer (Mac: `⇧⌘F`; Windows: `Ctrl+Shift+F`)
    - [x] Local repo is opened
  - [x] Open in External Editor (Mac: `⇧⌘A`; Windows: `Ctrl+Shift+A`); see External Editor option in prefs
    - [x] Secondary modal appears if no Editors set; option to Download Atom 
  - [x] Repository settings
    - [x] Remote path can be edited for existing repo; origin already set. Cannot be empty string, else error message.
      - [x] `Saved` button saves last entry
      - [x] `Cancel` button closes modal
    - [x] User can opt for `Setup custom remote` for a non-GitHub repository
      - [x] `Save & Publish` button saves last entry
      - [x] `Cancel` button closes modal
    - [x] Ignored Files
      - [x] `.gitignore` file contents are shown and can be edited
	- [x] `Saved` button saves last entry; changes create a new commit
	- [x] `Cancel` button closes modal
</details>

<details>
<summary>Branch top-level menu</summary>

  - [x] New Branch (Mac: `⇧⌘N`; Windows: `Ctrl+Shift+N`)
    - [x] Clicking `Create Branch` makes new branch based on the entered name, if not a duplicate
    - [x] Master branch is mentioned in the list; current branch shown first
    - [x] `Cancel` button closes modal
  - [x] Rename (cannot be master)
    - [x] `Rename` button changes branch name if field updated
      - [x] Same branch on GitHub.com is not renamed
    - [x] `Cancel` button closes modal
    - [x] Protected branches cannot be renamed
  - [x] Delete (cannot be master)
    - [x] Option to delete branch on the remote; default is unchecked
    - [x] `Delete` button deletes branch name (and remote too if option checked)
    - [x] `Cancel` button closes modal
    - [x] Protected branches cannot be deleted
  - [x] Update from Default Branch (cannot be master; Mac: `⇧⌘U`; Windows: `Ctrl+Shift+U`)
  - [x] Compare to Branch (Mac: `⇧⌘B`; Windows: `Ctrl+Shift+B`)
  - [x] Takes you to the `history` tab with the input selected so you can directly choose a branch
  - [x] Merge into Current Branch (Mac: `⇧⌘M`; Windows: `Ctrl+Shift+M`)
    - [x] Use can filter existing branches
    - [x] User can select branch, other than current
    - [x] `Merge` button only activated if something to merge
    - [x] `Cancel` button closes modal
  - [x] Compare on GitHub (Mac: `⇧⌘C`; Windows: `Ctrl+Shift+C`) (if repo already published on `github.com`)
  - [x] Create Pull request (Mac: `⌘R`; Windows: `Ctrl+R`) opens Pull Request on `github.com` 
    - [x] If branch unpublished, dialogue asks to publish the branch
    - [x] `Push Local Changes` modal surfaces with option to `Create Without Pushing` and `Push Commits`;(trigger: `Create Pull Request` after commit on branch before pushing)
</details>

<details>
<summary>Window top-level menu (Mac only)</summary>

  - [ ] Minimize, Zoom (maximize app size), Close, Bring All to Front, GitHub Desktop
</details>

<details>
<summary>Help top-level menu</summary>

  - [x] `Report Issue` opens issue template in Desktop repo on `github.com`
  - [x] `Contact GitHub Support` opens `https://github.com/contact` page with user and build prepopulated
  - [x] `Show User Guides` opens Desktop help page on `github.com`
  - [x] `Show Logs in Finder/Explorer` opens Finder/Explorer logs in local directory
    - [x] Mac: `ls ~/Library/Application\ Support/GitHub\ Desktop/logs/*.log`
    - [x] Windows: `%LOCALAPPDATA%\\Desktop\\*.desktop.production.log`
  - [x] About GitHub Desktop (Windows only)
</details>

<details>
<summary>Repositories list</summary>

  - [x] Current repo is always shown in top slot with respective icon; if repo exists
  - [x] Opening list shows all repos in categorized format with a working filter
    - [x] `ESC` clears the filter
    - [x] Search filter match results in bold characters
    - [x] All repos (private, enterprise, local, public, forked, other) have proper icon and found in the proper category (GitHub.com/Enterprise/Other)
      - [x] Hover shows username/repo, url, and/or local path in tooltip
      - [x] User must have paid account for private repos
      - [x] Repo icon is updated if admin changes status (public vs private)
  - [x] Repositories cloned from non-github servers should always be in the Other group, and have the 'computer' icon.
  - [x] Selecting a repo updates Changes/Compare/Diff areas
    - [x] If no Changes, Diff area shows `Open this repository` link to Finder/Explorer on local
  - [x] `Right-click` on any repo shows `Open in Terminal`, `Open in Finder/Explorer`, `Open in External Editor`, and `Remove` options
  - [x] Repos which have been removed locally (and trash emptied) have 'cannot find repository' warning
    - [x] Relaunching the app when it displays a missing repository preserves the repo's name and last seen path
    - [x] Remove a repo which can not be found (deleted locally & trash emptied)
  - [x] Repos which are cloning display a progress bar
</details>

<details>
<summary>History tab</summary>

  - [x] History tab shows `•` icon if files are waiting to be committed
    - [x] Number of changed files is always present; it can be 0
  - [x] Any changed files appear in the list, with respective +/•/- sign; with arrow keys enabled
    - [x] Merge-conflicted files shown with hazard icon; cannot be committed until fixed
    - [x] User can check none, or check one or more files to commit; list is scrollable
      - [x] User can select one or more lines to commit; diff is scrollable
      - [x] Right-clicking opens context menu
        - [x] User can discard the file; pending confirmation dialogue
	  - [x] `Do not show this message again`overrides the preference setting if true  
        - [x] User can ignore single/all files, show in Finder/Explorer, reveal in external editor, or open in default program
	  - [x] A specific files can only be ignored once
	  - [x] All ignored files found in Repository Settings > Ignored Files tab
	- User can open in finder, preferred editor, or OS default program  
  - [x] Panes can be resized horizontally, and contents resize to take the full width
    - [x] Quitting Desktop and relaunching remembers sizes
</details>

<details>
<summary>Compare tab</summary>

  - [x] Compare (was History) tab shows commits on your current branch by default
    - [x] All commits listed in chronological order, with avatar, date and name; list is scrollable with arrow keys enabled
      - [x] Right clicking any commit shows options: Revert, Copy SHA, View on GitHub
      - [x] Hover shows file name in tooltip
    - [x] Placing cursor in search field show all branches with number of commits behind/ahead  
    - [x] User can search to a target branch to filter commits; `esc` key to exit; autocomplete and text prediction intact
      - [x] User can toggle between behind/ahead, with counts shown
      - [x] Only commits behind/ahead shown
      - [x] User can merge in any commits into current branch for the "behind" tab
        - [x] After successful merge, tab counts update and merge button is disabled
        - [x] Merge conflict results in dialog shown directing user to commit view
</details>

<details>	
<summary>Relationship between branches</summary>

  - [x] Clicking in field with placeholder text `Select Branch to Compare…` shows a list of all branches and their number of commits ahead and behind the currently checked out branch
  - [x] Pressing `esc` key clears the current filter
  - [x] Filtering for branch name that doesn't exist shows "Sorry, I can't find that branch"
  - [x] Selecting a branch from the list populates the tab with that branch comparison data
    - [x] Behind tab is shown by default
      - [x] See number of commits behind in tab header
      - [x] If more than 0 commits behind, a list of commits are shown in reverse chronological order
      - [x] See button to merge into current branch (button disabled if 0 commits behind)
      - [x] Clicking the merge button shows merge conflicts if any, or successfully merges the commit(s)
      - [x] After merging, the comparison branch is 0 commits behind
    - [x] Ahead tab is on the right-hand side
      - [x] If more than 0 commits ahead, a list of commits are shown in reverse chronological order
    - [x] Can toggle between ahead/behind tabs using keyboard
  - [x] Clearing text in the `compare to branches` input on the `history tab` by pressing `x` takes you to the history view and clears the selected comparison branch
</details>

<details>
<summary>Diffs tab</summary>
		
  - [x] All commits have avatar, selectable SHA, # of files changed, commit message, commit description (optional)
    - [x] Long commit descriptions can be toggled with expand/collapse icon
      - [x] Reverting commit repopulates commit area
        - [x] Error message if no changes to commit
  - [x] All files within a commit listed, with respective +/•/-/-> sign; list is scrollable
    - [x] Diffs are viewable; list is scrollable with arrow keys enabled
      - [x] Green is for additions, red for deletions
      - [x] Different file types are rendered properly
      - [x] Single pic file with the `->` sign has multiple view options: 2-up (default); Swipe; Onion Skin; and Difference
  - [x] Panes can be resized horizontally, and contents resize to take the full width 
</details>

<details>
<summary>Commit section</summary>

  - [x] Commit created if user clicks `Commit to [branch]` button with commit message and at least one checked file
    - [x] `Fetch origin` changes to `Push` with number of commits badge
  - [x] Avatar of user is shown
  - [x] User can 'at-mention' those associated with the respective repo; either subject or description field is ok (published repositories only)
  - [x] User can 'pound-mention' an issue in the either subject or description field; issue number should populate (published repositories only)
  - [x] Description field is optional
  - [x] User can undo last commit
    - [x] `Push` with number of commits badge is decremented or reverts to `Fetch origin`
  - [x] `Undo` button disabled if user is pushing commit
  - [x] User can publish a new repo with no commits (aka unborn repo/branch)
  - [x] User can make new branch the default branch, by making the intial commit on the new branch.
  - [x] User can select individual files to commit at a time
</details>

<details>  
<summary>Co-authoring</summary>

  - [x] clicking co-author icon toggles co-author field; or right-click within commit area
    - [x] Hovering over the icon reveals add/remove 'action' text
    - [x] Right-click includes Mac/Windows context menus; option greyed out if repo not published to Github.com
    - [x] User can tag other GitHub.com users only, or those within your Enterprise org
      - [x] Tag is tied to public API name/email; email is "no-reply" if user setting is enabled
      - [x] Mouseover tooltip reveals name and email of any entered tags
      - [x] Tagging those outside of GitHub turns tag red
      - [x] You cannot tag a user more than once via the autocomplete; manually you can
      - [x] Typing a GitHub name not part of the initial autocomplete will initiate a search
        - [x] Found names are tagged; all others are turned red
        - [x] Navigating away from the History tab will clear red tags 
     - [x] Toggling the co-author icon clears the field
  - [x] All co-authors show up in Compare and diff view
    - [x] Commits with `Co-Authored-By: Name <username@github.com>`in the decription field reveal avatar of user    
    - [x] Hovering over an avatar reveals all tagged users
    - [x] Hovering over the "people" text reveals all names/emails of tagged users
  - [x] Undoing a commit re-enables the tags
  - [x] Reverting a commit does not re-enable the tags
</details>

<details>
<summary>Branches list</summary>

  - [x] Current branch always shows if repository present
    - [x] Hover shows full branch name in tooltip
    - [x] Long branch names are truncated, with beginning/end of branch name shown
  - [x] Opening list shows all branches in categorized format with a working filter
    - [x] `New` button opens 'New Branch' modal
    - [x] If filters results are nil, then prefill branch name in modal if user clicks `Create New Branch`
    - [x] Active branch is highlighted and marked with a check
    - [x] `ESC` clears the filter
    - [x] Search filter match results in bold characters
    - [x] Hover shows full branch name in tooltip
  - [x] Default branch labeled and listed first, with timestamp
  - [x] Selecting a branch switches branches
  - [x] Creating a new branch shows `Publish branch` button
    - [x] Publishing successful if logged in only; else error message
      - [x] `Create Pull Request` menu option shows warning if branch not published yet
  - [x] Renamed branches updated on .com and vice-versa if logged in; else error message
    - [x] Opens modal with ability to enter new name
  - [x] Deleted branches updated on .com and vice-versa if logged in; else error message
    - [x] Deleting branch show warning message
</details>

<details>
<summary>Fetching origin/Pull</summary>

  - [x] Code is constantly being fetched from .com with timestamp
     - [x] Hover shows timestamp in tooltip
    - [x] If Pull Requests on .com, they are reflected with down arrow and quantity
    - [x] Pull Requests and Commits can co-exist; error surfaces if merge commit
  - [x] User cannot Push/Pull without being signed in; error message surfaced
    - [x] Push/Pull works with public/private/Enterprise repos
    - [x] Tooltip shows status upon hover, if progress to display
  - [x] When a branch is local-only make sure that the `Fetch` button changes to `Publish` and it publishes
</details>
  
<details>
<summary>Publishing only</summary>

  - [x] Unpublished repository, unborn HEAD - `Publish button` enabled (user can publish repository)
  - [x] Unpublished repository, valid branch - `Publish button` enabled (user can publish repository and branch)
  - [x] Published repository, unborn HEAD - `Publish button` disabled (no branch to push)
  - [x] Published repository, branch without tracking - `Publish button` enabled (user can publish branch)
  - [x] Published repository, network action - `Publish button` disabled (don't interfere with existing action)
</details>
  
<details>
<summary>Pull Request list + CI status (v1.1)</summary>

 - [x] Pull request list shown as tab on Branch list
   - [x] Only open Pull Requests are reflected; closed Pull Requests not shown in the list
 - [x] Pull Request toolbar status is surfaced with yellow, green or red icon, or no icon if no status
 - [x] If no pull requests, then no badge shown, and Pull Request tab shows `0` 
   - [x] User shown current branch in text area, and given option to create a new branch or create new pull request
 - [x] Pull request for the current branch selected by default, with pull-request-number badge in header
   - [x] Pull request list can be filtered; `esc` key clears filter; arrow keys can scroll list
   - [x] Results in chronological order, with name, id number, date, username, and CI status
     - [x] Status checks run frequently in background, especially if yellow
     - [x] If user hovers over CI status icons, tooltips show individual/group status details
 - [x] PR status can be updated independently of respective PR
</details>

## Additional RBB scenarios

<details>
<summary>Branches</summary>

- [x] Try to compare branches when only master exists and see *"No Branches to Compare"*
  - [x] If there are no commits yet, then the rest of the history tab will be blank
  - [x] If commits, then the history tab will show history of commits
- [x] Compare branches when more than 1000 branches in a repository
  - [x] Confirm scrolling through branches is smooth
- [x] Changing default branch updates when selecting comparison branch
</details>

<details>
<summary>Commits</summary>

- [x] Add commits for a branch and confirm ahead/behind counts increment 
- [x] Choose branch to compare more than 1000 commits behind
  - [x] Confirm scrolling through commits is smooth
- [x] Choose branch to compare more than 1000 commits ahead
  - [x] Confirm scrolling through commits is smooth
</details>

<details>
<summary>Merge conflicts</summary>

- [x] Compare and merge branch that results in a merge conflict
  - [x] Close button closes modal
  - [x] View Conflicts button redirects to Commit view
</details>

<details>
<summary>General</summary>
- [x] Can compare branches when not signed in
- [x] Feature works with GitHub and GitHub enterprise accounts
</details>

## Testing notes
Interesting, weird, or other noteworthy things...

1. After creating a new repo, publishing and then adding another branch that has committed changes I still see `No Branches to Compare` under the History tab. https://github.com/desktop/desktop/issues/4755
![screen shot 2018-05-22 at 10 15 16 am](https://user-images.githubusercontent.com/10103121/40379027-f63145f6-5da9-11e8-8c51-42b9083a1616.png)
