### ISSUE TITLE
Testing Notes (NDDB)

### ISSUE THREAD

**Issue by meaghanlewis** [desktop/desktop#4982]
# General scenarios

### Notification dot and banner visibility

- [x] Notification dot and banner always visible when current branch diverges from default branch
  - [x] Switch between views
  - [x] Switch between branches
  - [x] Switch between repositories -> works but might need to fetch or switch branches first
- [x] Notification dot and banner visible until banner closed or commits are merged
- [x] Close notification banner. Make new commits on master and confirm dot and banner appear on current branch again
- [x] Banner text looks normal when > 10000 commits behind

### Change default branch
- [x] Notification banner stays open when comparing branches
- [x] Change default branch from master. Make commits. Confirm notification dot and banner appear on non default branches

### RBB
- [x] Compare master (default branch) with current branch and confirm that behind branch count matches the number of commits behind shown in notification banner

# Repository scenarios

Based off of the scenarios from #4874, thanks @iAmWillShepherd ❤️  

### Unpublished
- [x] Unpublished repository
  - [x] Publish and confirm that notification banner and dot still show
- [x] Unpublished enterprise repository

### Published
- [x] Published repository
- [x] Published repository with PR
- [x] Published fork repository (with changes from fork only)
- [x] Published fork repository (with changes from upstream)
- [x] Published fork repository (with changes from fork and upstream)
- [x] Enterprise repository
- [x] Enterprise fork repository
## Interesting things
- When I'm notified my branch has diverged and I switch between repositories, the notification doesn't always stay visible. If I switch to another repo with the notification, then all is well, but if I switch to a branch that doesn't have the notification and back I have to fetch or switch between branches to trigger the notification again.
![switch between repo nddb take 3](https://user-images.githubusercontent.com/10103121/41688995-59f20a20-74a3-11e8-96dc-bdb12bab9f90.gif)

## Questions
- How often does the automatic fetch happen? I have to fetch often to get the notification to appear and wondering if this interval can be changed for testing?
- If I dismiss the notification but then leave the branch and come back to it again should the notification appear or not?

**Comment by iAmWillShepherd** [comment]
> How often does the automatic fetch happen? 

The default fetch interval is 1 hour and is defined in `background-fetcher.ts`

> I have to fetch often to get the notification to appear and wondering if this interval can be changed for testing?

The interval can be updated if you are building from source. One thing to note is JS time is measured in milliseconds, so _1000 * 60 * 60_ is one hour.

https://github.com/desktop/desktop/blob/061fc8e21caf5640363ae8cdb4f3f9c5c09f6b5e/app/src/lib/stores/helpers/background-fetcher.ts#L11

**Comment by meaghanlewis** [comment]
![screen shot 2018-06-21 at 6 26 31 pm](https://user-images.githubusercontent.com/10103121/41753210-ceb26bd8-7580-11e8-93bc-1e310e795751.png)

Update message for when there is 1 **commit**

**Comment by shiftkey** [comment]
I'm going to close this out because I'm not sure what else needs to happen here. @meaghanlewis feel free to reopen if that's not the case.
