### ISSUE TITLE
Clarify and disambiguate roles of first responder and support

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#5486]
@steveward and I met this morning to chat about how we're handling [first responder rotation](https://github.com/desktop/desktop/blob/master/docs/process/first-responder.md) and his role as the support team member. The goal is to clearly disambiguate the two roles and draw clear lines of responsibility. To help get us there, a question and a few suggestions below. I'd like to update the first responder role doc to be clearer on expectations.

Questions:

1. Does first responder rotation still include reviewing PRs? If so, how do we handle when a non-dev is the first responder?

Suggestions:

- [x] Add a team for desktop/support so we can ping Steve in issues that require more support function (diagnosis of an individual's problem with the app or their setup).
- [ ] First responder responds to clarify the underlying problem, asks clarifying questions, and in that clarification, ping desktop/support if it's not obvious. If it's obvious, just give the answer.
- [ ] Goal is to respond within 24 hours on a weekday to initial issues and follow up replies. If first responder and Steve cannot meet this, they'll let us know in the channel to ask for help on specific portion(s) of the work.

cc: @desktop/core

**Comment by outofambit** [comment]
> Does first responder rotation still include reviewing PRs? If so, how do we handle when a non-dev is the first responder?

i would vote to decouple first responder from reviewing prs. my feeling is that @desktop/eng and @desktop/comrades as a group should be generally responsive on PRs (from maintainers as well as contributors), but i'd be curious to hear from others, too.

perhaps the suggested 24hr response time can be different for PRs after the intial response/acknowledgement? that feels more reasonable, especially depending on the size/complexity of the PR.

> Suggestions:

very in favor of these suggestions. i would add that pinging the product team may also be a suitable response when the answer isn't obvious. i guess it might be helpful to delineate expectations around "bug" issues and "feature request" issues?

**Comment by billygriffin** [comment]
Great stuff @outofambit. +1 on decoupling first responder from PR reviews, 24 hour response applying to issues but not follow up on PRs, and on pinging desktop/product as a reasonable part of issue triage when it's more of a user-facing question as opposed to a technical diagnosis or bug.

**Comment by billygriffin** [comment]
That seems reasonable @iAmWillShepherd. It seems like it would allow for PR reviews to happen in a reasonable timeframe without bogging everyone down. Open to others' thoughts though.

**Comment by outofambit** [comment]
> [...] I'm in agreement with @outofambit to decouple reviewing PRs from first-responder, but I think we should keep the PR piece if someone on @desktop/eng is on duty.

@iAmWillShepherd what do you mean by keeping the PR piece? that first responder should review all incoming PRs for that week? or something else?

**Comment by billygriffin** [comment]
Just want to add that as a deliverable prior to closing this out, I'd like to update the first responder documentation to reflect our shared thinking about how this should work.
