### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6478]
I’d like to rename the branch `master` to `development` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on `master`/`slave` terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `development`, though I do think it's a good fit for us now that we are in the practice of using release branches.)

## Technical Steps

- [x] create `development` branch from `master`
- [x] make `development` the default GitHub branch
- [x] modify github/central to use `development` for release notes reloading
- [x] redirect PRs to `development` in desktop/desktop
- [x] move branch protections from `master` to `development`
- [x] modify docs to reference `development` instead of `master`
- [x] delete `master` branch to avoid confusion?

(Thanks to @gr2m for prior thinking on this process)

## Related Issues and Projects

* https://github.com/django/django/pull/2692
* https://issues.apache.org/jira/browse/COUCHDB-2248
* https://www.drupal.org/node/2275877
* https://github.com/antirez/redis/issues/3185
* https://bugs.python.org/issue34605
* https://github.com/gr2m/octokit-rename-branch

**Comment by shiftkey** [comment]
In my head I'd always taken "master" to be borrowed from the concept of ["master copy"](https://www.collinsdictionary.com/dictionary/english/master-copy). I wanted to see if the Git contributors ever documented it somewhere but I couldn't find an early Git commit that mentions why `master` was chosen in that very first version. Maybe there's a mailing list thread, but at this point it's archaeological  (Git is almost 14 years old since that first very first commit was created) and it's for my curiosity more than anything.

So let's do it.

I'm 👍 on the rename for few other reasons:

 - words have meaning, and need to be appreciated in a wider context than "it's just code"
 - good names have value, and if there's a name that better describes what the default branch represents to us we should use it
 - by using a different branch to `master` for the `desktop` repository we're also developing and testing that GitHub Desktop has no leftover assumptions about the presence of a `master` branch

> (I’m open to names other than `development`, though I do think it's a good fit for us now that we are in the practice of using release branches.)

This is a chance for us to think about what the default branch represents - if it's going to be the latest, bleeding-edge code then the name should reflect that.

 I'm 👍 to `development` or even `dev` to save some keystrokes, but I'll let others chime in if they've got bright ideas.

**Comment by j-f1** [comment]
`main`?

**Comment by gr2m** [comment]
Hey thanks for pinging me! I love that you do this, I plan to do this myself. I've made a library that hopefully makes this a little easier: https://github.com/gr2m/octokit-rename-branch.

It automates a few of the steps you need to take, like updating all pull-request bases. Let me know if you have any questions or suggestions to further improve the script :)

**Comment by say25** [comment]
I have always been partial to the term `trunk`. Branches go off the trunk of a tree until they are no longer valid and are cut off.

**Comment by shiftkey** [comment]
> I have always been partial to the term `trunk`.  Branches go off the trunk of a tree until they are no longer valid and are cut off.

[Trunk Driven Development](https://trunkbaseddevelopment.com/) is also a great read if you want to learn more about this flow. 

I actually like this more than `development`, so that's currently got my vote.

**Comment by billygriffin** [comment]
Thanks @outofambit for kicking this off! In terms of the actual name, I don't have super strong feelings. I'd just say that as someone who has done some engineering but not a ton (and therefore more junior as a dev), `trunk` isn't super intuitive to me as the default branch - though I do understand the concept especially after the explanation.

Regardless of what we use, I'm glad we're now using release branches, which makes the idea of this as the default branch but not what we release from 👍 .

**Comment by suphanatnack** [comment]
1234

**Comment by outofambit** [comment]
I think i'm leaning towards `main` or `development` now. While I like the metaphor for `trunk`, I share @billygriffin's concern that it may be less legible to newer users.

**Comment by outofambit** [comment]
ok, i've opened all requisite PRs. will make the actual change of default branch to `development` in a couple hours and then redirect all PRs to point at that instead of `master`.

**Comment by gr2m** [comment]
@outofambit make sure to also update branch protection and the repository’s default branch

**Comment by outofambit** [comment]
@gr2m yes thank you! i had made a mental note of that but forgot to add it to the list above. updated!

**Comment by shiftkey** [comment]
Just a heads up: I had to change a couple of non-config settings around this change because PRs were not being run as usual:

 - Azure Pipelines config was still using `master` as the default branch
 - Codecov.io settings were still using `master` as the default branch

**Comment by outofambit** [comment]
I've deployed the remaining changes to central and deleted the `master` branch from this repo. Will close this issue once github/central#424 is merged. Thanks all!

**Comment by outofambit** [comment]
all done! ✨
