### ISSUE TITLE
[Tracking issue] Improve the ease of working with submodules

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#7523]
We've had several issues where people describe frustration with doing *x action* in GitHub Desktop when they're using submodules in their repo. Since it's tricky to understand the surface area of these issues, we wanted to at least start a tracking issue to roll up some of the other issues to make it easier to understand. We're not prioritizing this work currently, but hopefully this will allow us to have things in one place when we are able to work on it.

#### Relevant issues

- [x] https://github.com/desktop/desktop/issues/4592
- [x] https://github.com/desktop/desktop/issues/1770
- [ ] https://github.com/desktop/desktop/issues/6200
- [x] https://github.com/desktop/desktop/issues/4670
- [ ] https://github.com/desktop/desktop/issues/3242
- [x] https://github.com/desktop/desktop/issues/2344
- [x] https://github.com/desktop/desktop/issues/1870
- [x] https://github.com/desktop/desktop/issues/1803
- [x] https://github.com/desktop/desktop/issues/7519
- [x] https://github.com/desktop/desktop/issues/7624
- [x] https://github.com/desktop/desktop/issues/7823
- [x] https://github.com/desktop/desktop/issues/2579#issuecomment-513381961
- [x] https://github.com/desktop/desktop/issues/8554
- [x] https://github.com/desktop/desktop/issues/9174
- [x] https://github.com/desktop/desktop/issues/8221
- [x] https://github.com/desktop/desktop/issues/7691

**Comment by tierninho** [comment]
As part of these improvements, we should consider the following:

- Adding some UI treatment to a commit upon creation of a submodule. On GitHub.com there is a distinguishing icon for a submodule, but on Desktop it looks like any other file. 

<img width="437" alt="Screen Shot 2019-05-20 at 11 38 08 AM" src="https://user-images.githubusercontent.com/14828183/58053883-82686780-7af4-11e9-94f1-0fa4e7219c95.png">

- I suggest changing "[subproject](https://github.com/desktop/desktop/blob/development/app/test/fixtures/merge-parser/desktop/merge-submodule-diff-on-top-of-diff-changes-into-offline-mode-y-u-no-work.txt#L280)" to "submodule" to match verbiage elsewhere, unless we are purposefully using a broader term to encompass submodules, subtrees, and wrappers.

**Comment by pateskinasy** [comment]
Further add-on to the improvements list:

In cases where a submodule is another repo (in my case this other repo holds all images) I can only get the main repo to see newly added images to the submodule if I run an update command on the CLI. `git submodule update --recursive --remote --merge --force `

How to reproduce:
- Add new image to submodule (the separate repo).
- Commit changes to the submodule on Github Desktop.
- Main repo does not see new image when switching repos on Github desktop, no new commit suggestion shows up.
- I run my CLI build command to try to get the update to happen (In my case `gulp`). The build completes without the new image.
- I run `git submodule update --recursive --remote --merge --force ` and now my main repo sees the image. I now get a commit suggestion on Github Desktop for the new image on the Main repo.
- My CD system now completes the build with the new image.

Desired output:
- Add new image to submodule (the separate repo).
- Commit changes to the submodule on Github Desktop.
- Main repo sees new image when switching repos on Github desktop, a new commit suggestion shows up.

**Comment by tierninho** [comment]
@pateskinasy Thank you for adding the steps for this issue. I have created a [new issue](https://github.com/desktop/desktop/issues/7624) for you suggestion, so it doesn't get lost.

**Comment by IncludeSec** [comment]
Hi @billygriffin it looks like some of these are slowly being closed. We'd love to put our vote in for addressing the Authentication issue: #2579 !

**Comment by billygriffin** [comment]
Thanks @IncludeSec! This isn't an area of the app we're actively working on at the moment, but we'll certainly update this issue (and the other one) when we are able to pick it up.

**Comment by drawcode** [comment]
Would love for this to become a priority at some point. 

Submodules really help with shared tech and larger repos without having to route some of those libs through packages.

SourceTree has submodule tools, how they solve it is you can open up each submodule in gitmodules in another window prior to commit/push of the containing repo and then do all the normal actions in that new window, then close and push the module tracking hash after update.

Github Desktop doesn't have multiple windows yet (#3606) which would make implementing submodules easier. Dealing with submodules you have to go to the CLI which is fine for now. With multiple windows/instances, both of these features are probably doable and the tool improves greatly. It probably makes it easier to deal with submodules in a separate instance/window in addition to the help when dealing with multiple projects.

Thanks for all your work on this and it is why we love Github. The tool has gotten better and better. Hopefully multiple instances and submodules are a priority soon!

**Comment by amitaiab** [comment]
Hi,


As a user, I think it would be most easier if the Fetch button will also be toolbar-dropdown type (same as Current Repository and Current Branch, while the Fetch is toolbar-button).
Then , pressing the Fetch toolbar-dropdown will open a list of Submodules, and when choosing a specific Submodule, it will fetch all for the Submodule folder.


![githubdesktop](https://user-images.githubusercontent.com/108336460/178485163-399fed83-de0d-42be-9c5e-6f1150d04b03.PNG)

**Comment by steveward** [comment]
Request to automatically add submodules and implement a tree view in https://github.com/desktop/desktop/issues/15084.

**Comment by sergiou87** [comment]
With the latest changes in #15176 #15237 #15240 I think we have tackled almost all of the issues tracked here, and we can safely close this.

Feedback from the new UX will be tracked in new issues and evaluated separately.

Thank you all for your feedback!

**Comment by sergiou87** [comment]
I forgot to mention, these improvements are available in the latest beta 3.0.8-beta1 that you can download from https://desktop.github.com/beta

If everything goes 👍 we'll release these to production in the upcoming weeks.

**Comment by grochoge** [comment]
@sergiou87 Neither the release or beta versions of GitHub Desktop work correctly when switching from a master branch without submodules to a branch with submodules. Should that be a new issue or re-open one of the existing ones?
```
fatal: not a git repository: ../../.git/modules/Submodules/CommonCode
fatal: could not reset submodule index
```

It appears `git checkout --recurse-submodules` is broken.

**Comment by sergiou87** [comment]
@grochoge could you try running `git submodule update --init --recursive` in your repository and see if that solves the issue? 🤔

**Comment by TheLastRar** [comment]
> @grochoge could you try running `git submodule update --init --recursive` in your repository and see if that solves the issue? 🤔

I have a similar issue, I'm switching from one branch to the main branch, the main branch has an extra submodule,
I get a similar error to @grochoge, and github aborts the branch change
running `git submodule update --init --recursive` does not fix the issue
This issue is reported here https://github.com/desktop/desktop/issues/13016, which was incorrectly closed (as a duplicate of itself?)

**Comment by yrafaf** [comment]
> @TheLastRar  I have a similar issue, I'm switching from one branch to the main branch, the main branch has an extra submodule, I get a similar error to @grochoge, and github aborts the branch change running `git submodule update --init --recursive` does not fix the issue This issue is reported here #13016, which was incorrectly closed (as a duplicate of itself?)

I m having exactly the same issue, and I m wondering  if you managed to solve the problem please ?

**Comment by TheLastRar** [comment]
> > @TheLastRar  I have a similar issue, I'm switching from one branch to the main branch, the main branch has an extra submodule, I get a similar error to @grochoge, and github aborts the branch change running `git submodule update --init --recursive` does not fix the issue This issue is reported here #13016, which was incorrectly closed (as a duplicate of itself?)
> 
> I m having exactly the same issue, and I m wondering if you managed to solve the problem please ?

Yes I did, however, it has been a while since I've had to solve this issue and I don't recall exactly what I did.
I _think_ it involved checking out a commit on the main branch before the submodule was added (it was at the time a recent change), before then continuing to the latest commit.

I should have made notes for me to refer to, as I had run into this issue numerous times and always struggled to figure out how to fix it.

**Comment by yrafaf** [comment]
YES, I understand you, thank you so much for your answer 

> > > @TheLastRar  I have a similar issue, I'm switching from one branch to the main branch, the main branch has an extra submodule, I get a similar error to @grochoge, and github aborts the branch change running `git submodule update --init --recursive` does not fix the issue This issue is reported here #13016, which was incorrectly closed (as a duplicate of itself?)
> > 
> > 
> > I m having exactly the same issue, and I m wondering if you managed to solve the problem please ?
> 
> Yes I did, however, it has been a while since I've had to solve this issue and I don't recall exactly what I did. I _think_ it involved checking out a commit on the main branch before the submodule was added (it was at the time a recent change), before then continuing to the latest commit.
> 
> I should have made notes for me to refer to, as I had run into this issue numerous times and always struggled to figure out how to fix it.
