### ISSUE TITLE
[Onboarding] Resolve copy inconsistencies

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#8262]
check copy on tutorial steps and instructions for inconsistencies with the existing UI that might be confusing. decide if/how we want to resolve them:

- [ ] push branch vs publish branch
- [ ] others?

/cc @ampinsk @kuychaco @billygriffin

**Comment by tierninho** [comment]
- [ ] External editor (see prefs) vs text editor (see copy)
- [ ] Create a branch (see GH lingo/help docs) vs make a branch (see copy)
- [ ] Summary/description (see field names) vs message (see copy)
- [ ] ⌘G (see View menu) vs ⌘ Enter (see copy)

Open editor or open repository or edit file? At first glance it can be confusing.
![Screen Shot 2019-09-13 at 11 32 40 AM](https://user-images.githubusercontent.com/14828183/64896104-4d8b9d80-d61a-11e9-984d-213530b3904e.png)

What if there is no colleague to view it? I suppose they can skip it.
![Screen Shot 2019-09-13 at 11 33 17 AM](https://user-images.githubusercontent.com/14828183/64896106-4e243400-d61a-11e9-8ea5-bc980e81b16f.png)

**Comment by outofambit** [comment]
@ampinsk did we address all of these in #8294 ? (aka should we close this or leave it open?)

**Comment by billygriffin** [comment]
I think we're good for now on this issue. There are definitely going to be a few more that come out of usability testing, but I'm comfortable closing this.
